version: '3.8'

services:
  poseidon-sage:
    build: .
    container_name: poseidon-params-generator
    volumes:
      - ./output:/home/sage/output
    working_dir: /home/sage
    command: >
      bash -c "
        echo 'Generating Poseidon parameters for Pallas curve...' &&
        echo 'Prime modulus: 0x40000000000000000000000000000000224698fc094cf91b992d30ed00000001' &&
        echo '' &&
        echo 'Configuration 1: t=3, alpha=5' &&
        sage generate_params_poseidon.sage 1 0 255 3 5 128 0x40000000000000000000000000000000224698fc094cf91b992d30ed00000001 &&
        echo '' &&
        echo 'Configuration 2: t=5, alpha=5' &&
        sage generate_params_poseidon.sage 1 0 255 5 5 128 0x40000000000000000000000000000000224698fc094cf91b992d30ed00000001 &&
        echo '' &&
        echo 'Configuration 3: t=9, alpha=5' &&
        sage generate_params_poseidon.sage 1 0 255 9 5 128 0x40000000000000000000000000000000224698fc094cf91b992d30ed00000001 &&
        echo '' &&
        echo 'Configuration 4: t=3, alpha=3' &&
        sage generate_params_poseidon.sage 1 0 255 3 3 128 0x40000000000000000000000000000000224698fc094cf91b992d30ed00000001 &&
        echo '' &&
        echo 'Copying results to output directory...' &&
        mkdir -p output &&
        cp *.txt output/ 2>/dev/null || echo 'No .txt files found' &&
        echo 'Generated files:' &&
        ls -la *.txt 2>/dev/null || echo 'No parameter files generated'
      "